export const KAFKA_TOPICS = {
  ORDER_EVENTS: "order-events",
  PAYMENT_EVENTS: "payment-events",
  KITCHEN_EVENTS: "kitchen-events",
  DELIVERY_EVENTS: "delivery-events",
  NOTIFICATION_EVENTS: "notification-events",
};

export const KAFKA_EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",

  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  FOOD_PREPARING: "FOOD_PREPARING",
  FOOD_READY: "FOOD_READY",

  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  DELIVERY_ACCEPTED: "DELIVERY_ACCEPTED",
  FOOD_PICKED_UP: "FOOD_PICKED_UP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  REACHED_LOCATION: "REACHED_LOCATION",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  DELIVERY_ISSUE: "DELIVERY_ISSUE",

  SEND_NOTIFICATION: "SEND_NOTIFICATION",
};
